---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-configured
  labels:
    app: nginx-configured
spec:
  containers:
  - name: nginx
    image: nginx:1.18.0    # image to use https://hub.docker.com/_/nginx
    ports:
    - containerPort: 80
    volumeMounts:         # these 3 files are to be injected into the system
    - name: nginx-proxy-config     # this matches spec.volumes.name[0] below
      mountPath: /etc/nginx/nginx.conf   # we want to be able to find this from within the container
      subPath: nginx.conf    # req. because this file already exists in the container
    - name: my-index-file          # this matches spec.volumes.name[1] below
      mountPath: /var/www/index.html     # we want to be able to find this from within the container
      subPath: index.html          # req. because this file already exists in the container
    - name: static-demo-data       # this matches spec.volumes.name[2] below
      mountPath: /var/www/static/nginx.txt   # we want to be able to find this from within the container
      subPath: nginx.txt              # req. because this file already exists in the container
  volumes:
  - name: nginx-proxy-config   # matches spec.containers[0]volumeMounts[0]name above
    configMap:
      name: nginx-conf     # you MUST have created nginx-conf configmap with kubectl
  - name: my-index-file   # matches spec.containers[0]volumeMounts[1]name above
    configMap:
      name: index-file     # you MUST have created index-file configmap with kubectl
  - name: static-demo-data   # matches spec.containers[0]volumeMounts[2]name above
    configMap:
      name: nginx-txt      # you MUST have created nginx-txt configmap with kubectl

